coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/fixtures/**/*"
  - "**/*.test.ts"
  - "dist/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
